### ISSUE TITLE
Is the current build stable?

### ISSUE THREAD

**Issue by dr01d3r** [susom/redcap-em-trackcovid-appointment-scheduler#1]
@123andy @ihabzee I see this isn't in the EM Repo yet, and there are no releases.  Is the master branch stable for use/testing?  One of our users has interest in this as a participant self-scheduling solution.

**Comment by 123andy** [comment]
There are a few flavors of this - I’ll let Ihab elaborate.  Born of the COVID madness they work but probably could be improved.  Do do use them in prod still.
________________________________
From: Chris Kadolph ***@***.***>
Sent: Wednesday, February 8, 2023 1:19:17 PM
To: susom/redcap-em-trackcovid-appointment-scheduler ***@***.***>
Cc: Andy Martin ***@***.***>; Mention ***@***.***>
Subject: [susom/redcap-em-trackcovid-appointment-scheduler] Is the current build stable? (Issue #1)


@123andy<https://github.com/123andy> @ihabzee<https://github.com/ihabzee> I see this isn't in the EM Repo yet, and there are no releases. Is the master branch stable for use/testing? One of our users has interest in this as a participant self-scheduling solution.

**Comment by ihabzee** [comment]
Hi @dr01d3r the EM is stable but heavily customized to an old COVID project. As Andy mentioned we have different flavors of this scheduler. Can you provide more details about your use case? We have a standalone scheduler that is open to any participant to pick a time and book it. In another scheduler flavor(works with longitude projects) a participant will have their booking page (with login credentials). The participant can book multiple appointments during a study spread over multiple arms/events.

**Comment by dr01d3r** [comment]
Sorry for the very late response here, but our analyst found a "creative use" solution for this.  I do appreciate your response, though.
